services:
  
  db:
    container_name: postgres_DB
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
    networks:
      - my_network
    volumes:
      - postgres_volume:/var/lib/postgresql/data 

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - my_network

  backend-service:
    build: .
    depends_on:
      - db
      - adminer
    volumes:
      - ../:/var/www/myapp
    networks:
      - my_network
    ports:
      - 5000:5000
  

networks:
  my_network:
    driver: bridge

volumes:
  postgres_volume: